global:
  # How frequently to scrape targets by default. default = 1m
  scrape_interval: 5s

  # How long until a scrape request times out. default = 10s
  scrape_timeout: 5s

  # How frequently to evaluate rules. default = 1m
  evaluation_interval: 1m

 
remote_read:
  - url: "http://promscale:9201/read"
    read_recent: true

# Promscale settings https://github.com/timescale/promscale/blob/master/docs/configuring_prometheus.md
remote_write:
  - url: "http://promscale:9201/write"
    remote_timeout: 30s
    queue_config:
      capacity: 10000
      max_samples_per_send: 3000
      batch_send_deadline: 10s
      min_shards: 4
      max_shards: 200
      min_backoff: 100ms
      max_backoff: 10s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'wildfly'
    static_configs:
      - targets: ['wildfly1:9990', 'wildfly2:9990', 'wildfly3:9990', 'wildfly4:9990']
